### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by spirali** [spirali/elsie#5]
- [x] values "next", "next+" for step argument. ("next" is replaced by smallest non-used step in the slide)
- [x] recompute missing height/width for image 
- [x] render(drop_redundant_slides=True) (if two completely identical consecutive slides are generated, then only one is left)
- [x] bitmap pictures directly usable in .image() method
- [x] "return self" in box method where it makes sense (.text, .code, .image)
